name = "karthik-www-theme"
description = "Theme for karthik-www blog"
homepage = "https://karthikganeshram.com"
min_version = "0.128.0"

[author]
name = "Karthik Ganeshram"
homepage = "https://karthikganeshram.com"
